version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=dbpresta
      - POSTGRES_USER=xhepo
      - POSTGRES_PASSWORD=xhepower
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
